name: parkme
description: Your parking partner

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_stripe: ^9.5.0
  
  # UI & Icons
  cupertino_icons: ^1.0.6
  
  # Firebase
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  firebase_auth_web: ^5.15.2
  # Maps & Location
  google_maps_flutter: ^2.12.3
  google_maps_flutter_web: ^0.5.12+2 
  geolocator: ^10.1.0
  geocoding: ^2.1.0
  # Authentication
  google_sign_in: ^7.1.1
  
  # QR Code
  qr_flutter: ^4.1.0
  
  # Payment
  razorpay_flutter: ^1.4.0
  mpesa_flutter_plugin: ^1.6.1
  
  # UI Components
  fluttertoast: ^8.2.4
  carousel_slider: ^5.1.1
  
  # Communication
  twilio_flutter: ^0.0.9
  flutter_paystack: ^1.0.7
  # Permission handling (you'll likely need this)
  permission_handler: ^11.1.0
  intl: ^0.17.0
  firebase_database: ^11.3.9

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/parkmeIcon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/